version: '3'

services:
  master:
    image: redis:alpine
    ports:
      - 6379:6379
  replica_1:
    image: redis:alpine
    ports:
      - 6380:6379
    command: redis-server --replicaof master 6379
  replica_2:
    image: redis:alpine
    ports:
      - 6381:6379
    command: redis-server --replicaof master 6379
  replica_3:
    image: redis:alpine
    ports:
      - 6382:6379
    command: redis-server --replicaof replica_1 6379
