version: '3'

services:
  master:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  replica_1:
    image: redis:alpine
    ports:
      - 6380:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof master 6379
  replica_2:
    image: redis:alpine
    ports:
      - 6381:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof master 6379
  replica_3:
    image: redis:alpine
    ports:
      - 6382:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof replica_1 6379
